# VS Code editor
visual-studio-code-bin
# JetBrains Toolbox (for managing JetBrains IDEs)
jetbrains-toolbox
# Google Chrome browser
google-chrome
# Tuxedo Control Center (for managing power profiles and other settings on Tuxedo laptops)
tuxedo-control-center-bin tuxedo-drivers-dkms
# Icon themes
candy-icons-git 
# Plymouth themes
plymouth-theme-loader-alt-git
# Sddm themes
archlinux-themes-sddm