# VS Code editor
visual-studio-code-bin
# JetBrains Toolbox (for managing JetBrains IDEs)
jetbrains-toolbox
# Google Chrome + Helium browser
google-chrome helium-browser-bin
# Tuxedo Control Center (for managing power profiles and other settings on Tuxedo laptops)
tuxedo-control-center-bin tuxedo-drivers-dkms
# Icon themes
candy-icons-git 
# Plymouth themes
plymouth-theme-loader-alt-git
# Timeshift (backups) timer
timeshift-systemd-timer
# Sddm themes
archlinux-themes-sddm
# Hyprland stuff
hyprshell-bin hyprsysteminfo