org.torproject.torbrowser-launcher 
# Video editor
org.shotcut.Shotcut 
org.onlyoffice.desktopeditors 
org.libreoffice.LibreOffice 
org.inkscape.Inkscape 
org.gnome.clocks 
# Disk usage analyzer
org.gnome.baobab
# Camera
org.gnome.Snapshot 
org.gnome.PowerStats 
# Document viewer
org.gnome.Evince 
org.gnome.Calculator 
org.gnome.Boxes 
org.gimp.GIMP 
net.nokyan.Resources 
md.obsidian.Obsidian 
io.missioncenter.MissionCenter 
# Switcheroo (convert images)
io.gitlab.adhami3310.Converter 
# Manage flatpaks
io.github.flattool.Warehouse 
# Flatpak app permissions manager
com.github.tchx84.Flatseal 
com.usebottles.bottles 
com.spotify.Client 
com.obsproject.Studio 
com.getpostman.Postman
com.github.xournalpp.xournalpp 
cc.arduino.IDE2
# Appimage Manager
it.mijorus.gearlever