# DE
hyprland
# Pick Colors from screen
hyprpicker 
# Idle manager (calls hyprlock)
hypridle 
# Lockscreen
hyprlock 
# Handle desktop portals for hyprland (file chooser, screenrecording, etc.)
xdg-desktop-portal-hyprland 
# Wallpaper setter for hyprland
hyprpaper
# Polkit agent for hyprland
hyprpolkitagent 
# Hyprland Cursor format
hyprcursor
# Hyprland QT support
hyprland-qt-support