# Base packages
less zsh tree tmux openssh shadow man make jq zstd ffmpeg
# Base system (Net and Audio)
networkmanager pipewire pipewire-alsa pipewire-audio pipewire-jack pipewire-pulse 
# Lists open files for running Unix processes
lsof
# FS / Disk tools
btrfs-progs e2fsprogs exfat-utils dosfstools exfatprogs nvme-cli smartmontools gparted
# Fonts
ttf-jetbrains-mono-nerd noto-fonts cantarell-fonts
# GPU
rocm-smi-lib
# Firmware and microcode
intel-ucode 
# Other Tools
micro git ncdu htop btop upower powertop brightnessctl yazi
# Improved Tools
zoxide fzf ripgrep eza fd just
# Blutooth
bluez 
# Boot animation
plymouth 
# Report packages 
pkgstats
# Container tooling
podman podman-compose distrobox 
# ZSH Plugins
zsh-autosuggestions zsh-completions zsh-history-substring-search zsh-syntax-highlighting
# Nix
nix