# Base packages
less zsh tree tmux openssh shadow man make jq zstd ffmpeg
# Base system (Net and Audio)
networkmanager pipewire pipewire-alsa pipewire-audio pipewire-jack pipewire-pulse 
# Lists open files for running Unix processes
lsof
# FS / Disk tools
btrfs-progs btrfs-assistant e2fsprogs exfat-utils dosfstools exfatprogs nvme-cli smartmontools gparted
# Fonts
noto-fonts noto-fonts-emoji cantarell-fonts adwaita-fonts dejavu-fonts
# Nerd Fonts
ttf-jetbrains-mono-nerd ttf-nerd-fonts-symbols
# GPU
rocm-smi-lib
# Firmware and microcode
intel-ucode 
# Other Tools
micro git ncdu htop btop upower powertop brightnessctl yazi age
# Improved Tools
zoxide fzf ripgrep eza fd
# Blutooth
bluez 
# Boot animation
plymouth 
# Report packages 
pkgstats
# Container tooling
podman podman-compose distrobox 
# ZSH Plugins
zsh-autosuggestions zsh-completions zsh-history-substring-search zsh-syntax-highlighting
# Nix
nix
# Compression tools
7zip unzip
# Timeshift (backups)
timeshift