# Terminal
alacritty 
# Browsers (not installed as flatpaks)
firefox chromium
# Audio and video configuration 
pavucontrol 
# Login Manager
sddm
# Screenshots
slurp grim swappy
# Container tooling
podman-desktop 
# App launchers
rofi fuzzel
# Yad icon browser
yad 
# PDF viewer
evince
# Mount Smartphones (MTP)
gvfs-mtp
# File manager
nautilus thunar
# Other Tools
mpv wl-clipboard playerctl ydotool
# Notifications
dunst
# Automount Drives
udiskie
# Bar
waybar
# Gnome tools
gnome-tweaks gnome-keyring gnome-software gnome-autoar gnome-bluetooth-3.0 gnome-disk-utility gnome-disk-utility gnome-keyring gnome-power-manager 
xdg-desktop-portal-gnome
