HISTFILE=~/.histfile
HISTSIZE=5000
SAVEHIST=10000
setopt autocd extendedglob nomatch notify incappendhistory
setopt HIST_IGNORE_SPACE
unsetopt beep
bindkey -e
export EDITOR=micro

zstyle ':compinstall filename ' ret '~/.zshrc'
autoload -Uz +X compinit && compinit
autoload -Uz +X bashcompinit && bashcompinit

## custom
eval "$(zoxide init zsh)"

alias cd="z";
alias ls="eza -a";
alias ll="eza -lahg --icons --git";
alias grep="rg";

bindkey "^[[1;5C" forward-word;
bindkey "^[[1;5D" backward-word;
bindkey "^[[3~" delete-char;

function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	yazi "$@" --cwd-file="$tmp"
	IFS= read -r -d '' cwd < "$tmp"
	[ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd"
	rm -f -- "$tmp"
}

source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh