#
# /etc/pacman.conf
#
# See the pacman.conf(5) manpage for option and repository directives

[options]
DBPath       = /usr/lib/sysimage/lib/pacman/
CacheDir     = /usr/lib/sysimage/cache/pacman/pkg/
LogFile      = /usr/lib/sysimage/log/pacman.log
HoldPkg      = pacman glibc
Architecture = auto


Color
CheckSpace
VerbosePkgLists
ParallelDownloads = 10
DisableSandboxFilesystem
ILoveCandy

SigLevel          = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist