name: build-and-push

on:
  schedule:
    # Run at 3:00 AM every Saturday
    - cron: "0 3 * * 6"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install podman
        run: sudo apt-get update && sudo apt-get install -y podman

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | sudo podman login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Set image name
        run: |
          echo "IMAGE_REPO=$(echo 'ghcr.io/${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"

      - name: Build base image
        run: |
          set -euo pipefail

          sudo podman build --network=host -f Containerfile -t "${IMAGE_REPO}-base:weekly" .
          echo "Built base image: ${IMAGE_REPO}-base:weekly"

      - name: Build chunked image with chunkah
        run: |
          set -euo pipefail

          export CHUNKAH_CONFIG_STR="$(sudo podman inspect "${IMAGE_REPO}-base:weekly")"
          echo "Config: $CHUNKAH_CONFIG_STR"
          sudo podman run --rm -v $(pwd):/out --mount=type=image,src="${IMAGE_REPO}-base:weekly",target=/chunkah -e CHUNKAH_CONFIG_STR \
            quay.io/coreos/chunkah build -v --label containers.bootc=1 --label ostree.bootable=1 --max-layers 400 -o /out/image
          
          echo "Built chunked image: ${IMAGE_REPO}:weekly"
          
          sudo podman load -i $(pwd)/image > out
          sudo podman tag "$(awk -F'sha256:' '/sha256:/ {print $2}' out)" "${IMAGE_REPO}:weekly"

          echo "Loaded chunked image: ${IMAGE_REPO}:weekly"

      - name: Push chunked image
        run: sudo podman push "${IMAGE_REPO}:weekly"
